### ISSUE TITLE
Handle ShutdownSignalException In Receiver

### ISSUE THREAD

**Issue by dbuos** [reactor/reactor-rabbitmq#34]
Actually the Receiver does not handle ShutdownSignalException thus when the Broker goes down, the Flux of messages simply stop the signal emissions and never terminates leaving the application code with no means of recovery for this type of failure.
This may be fixed by using 

basicConsume(String queue, boolean autoAck, DeliverCallback deliverCallback, ConsumerShutdownSignalCallback shutdownSignalCallback)

instead of:
final String consumerTag = channel.basicConsume(queue, false, deliverCallback, cancelCallback);

wich only receives cancelCallback thus ignoring shutdownSignals

**Comment by acogoluegnes** [comment]
Just to make sure I understand the use case correctly, under which circumstances does the problem come up? Receiver supports connection recovery, so I guess this would be when the application stops and closes the connection, you'd like the client code of the `Flux` to know about this, right?

**Comment by Daniel69** [comment]
Hi, @acogoluegnes, thank you for the response, I figured out what the problem was, I'm using a connection from a external connectionFactory that sets AutomaticRecoveryEnabled to false `connectionFactory.setAutomaticRecoveryEnabled(false)` thus the error raises when the broker connections was lost. I think that this should be fixed having automatic recovery enabled in my connection factory.  Thanks a lot.

**Comment by acogoluegnes** [comment]
@dbuos I added a fix anyway to complete the flux when the channel is closed under normal circumstances (i.e. when auto-recovery wouldn't happen). Thanks for pointing this up.
