### ISSUE TITLE
Channel creation - error handling during publishing support

### ISSUE THREAD

**Issue by pmackowski** [reactor/reactor-rabbitmq#41]
ExceptionHandler assumes existence of a channel, whereas `Sender#send` or `Sender#sendWithPublisherConfirms` might fail earlier during channel creation (with exception `AlreadyClosedException`|`ShutdownSignalException`). In such case publishing will not be retried.

Currently we can only customize retrying channel.basicPublish through `SendOptions`.
It would be great to have such an option for a channel creation. Are you planning to add it in future releases?

Simple workaround is to use reactor retry or retryWhen operators so it is not must-have but it can be misleading especially to new users expecting retry for `ShutdownSignalException`.

**Comment by acogoluegnes** [comment]
Thanks for the workaround, this is very informative. Can you please elaborate on the reason the workaround doesn't work because of caching?

Note the connection caching can be disabled by passing in a custom `Mono<Connection>`.

Note also that `Sender#send` and `Sender#sendWithPublishConfirms` should behave the same, I don't remember any reason to cache the channel in one case and not in the other, so this is likely to be an unfortunate bug. That'll be fixed if we introduce a `Mono<Channel>` in `SendOptions` for 1.1.0.

**Comment by pmackowski** [comment]
When caching is enabled for Mono<Connection> or channel creation retry always gets the same signal from upstream which might be an error signal. In such case retry does not help even if rabbitmq is again up and running.

I haven't noticed that we can customize Mono<Connection> through SenderOptions. Thanks for information. 

Regarding `Sender#send` and `Sender#sendWithPublishConfirms` the difference is here [send](https://github.com/reactor/reactor-rabbitmq/blob/master/src/main/java/reactor/rabbitmq/Sender.java#L105) and here [sendWithPublishConfirms](https://github.com/reactor/reactor-rabbitmq/blob/master/src/main/java/reactor/rabbitmq/Sender.java#L144). It seems that the latter implementation without caching is better.

**Comment by acogoluegnes** [comment]
Closed by #42.
