### ISSUE TITLE
Receiver Consuming Multiple Queues

### ISSUE THREAD

**Issue by mrnewton7** [reactor/reactor-rabbitmq#57]
The sample receiver was a great start for me. My team has a use case where we need our Spring Boot Reactor RabbitMQ application to consume messages from several (~15) queues. Is there a recommended pattern that we should follow or is it as simple as creating new receiver objects for each queue?

**Comment by acogoluegnes** [comment]
Thanks for using Reactor RabbitMQ, glad to see the sample turned out to be useful. You don't have to create new `Receiver` instances, you can use only one and call `consume*` for each queue. This wouldn't apply if the queues were on different hosts, you would need different connections and so different `Receiver` instances.

**Comment by mrnewton7** [comment]
@acogoluegnes Thank you for the quick response on this. If I have further reactor rabbitmq questions where is the best place to ask those?

**Comment by acogoluegnes** [comment]
@mrnewton7 I added a few links: https://github.com/reactor/reactor-rabbitmq#community--support. A good place is Gitter, make sure to cc me (@acogoluegnes).
